<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>Fable.Expect.Unofficial</PackageId>
    <Description>Utilities to test Fable apps. Unofficial build of Fable.Expect, republished from a fork while fixes are pending upstream at github.com/fable-compiler/Fable.Expect.</Description>
    <TargetFramework>netstandard2.0</TargetFramework>
    <NpmDependencies>
      <NpmPackage Name="@web/test-runner" Version="gte 0.13.18" ResolutionStrategy="Max" DevDependency="true" />
      <NpmPackage Name="@web/test-runner-commands" Version="gte 0.5.13" ResolutionStrategy="Max" DevDependency="true" />
    </NpmDependencies>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Expect.fs" />
    <Compile Include="Expect.Dom.fs" />
    <Compile Include="Expect.Elmish.fs" />
    <Compile Include="WebTestRunner.fs" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="*.fsproj; *.fs; *.js" PackagePath="fable\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Fable.Browser.Dom" Version="2.20.0" />
    <PackageReference Include="Fable.Core" Version="4.5.0" />
    <PackageReference Include="Fable.Elmish" Version="5.0.2" />
    <PackageReference Include="Fable.Promise" Version="3.2.0" />
  </ItemGroup>
</Project>